services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        entrypoint: >
            bash -c "sleep infinity"
        tty: true
        stdin_open: true
        init: true
        env_file:
            - .env
